import { Mission, EvidenceItem } from '../types';

export const MISSIONS_REGISTRY: Record<string, Mission> = {
  'mission-python-core': {
    id: 'mission-python-core',
    title: 'Mission: Build an Automated Log & Expense Parser',
    objective: 'Write a Python function that parses transaction strings, categorizes them, filters expenses above a threshold, and computes the sum.',
    scenario: 'You are helping a finance team automate incoming daily receipt streams. Raw receipt strings arrive formatted as "Category: Amount, Category: Amount".',
    whatYouNeed: ['Python strings & split()', 'Dictionary data structure', 'List comprehension', 'Type casting (float/int)'],
    steps: [
      {
        id: 'step-1',
        instruction: 'Split the raw CSV line into individual transaction pairs.',
        hint: 'Use raw_text.split(",") to obtain an array of token pairs.',
        testCheck: 'Splits raw string into array of items',
      },
      {
        id: 'step-2',
        instruction: 'Parse category names and numeric values into a structured dictionary.',
        hint: 'Iterate over tokens and split by ":" while trimming whitespace with .strip().',
        testCheck: 'Converts strings to floats and stores in dictionary',
      },
      {
        id: 'step-3',
        instruction: 'Calculate the total expense and return only categories with amounts > 50.',
        hint: 'Use a dictionary comprehension {k: v for k, v in expenses.items() if v > 50}.',
        testCheck: 'Filters expenses above threshold and calculates sum',
      },
    ],
    starterCode: `def parse_expenses(raw_data: str, threshold: float = 50.0):\n    """\n    Input format: 'Food: 25.50, Electronics: 120.00, Groceries: 45.00, Travel: 85.20'\n    Return: dict with total, count, and filtered items over threshold.\n    """\n    # 1. Parse raw_data\n    expenses = {}\n    # YOUR CODE HERE\n    \n    return {\n        "total": 0.0,\n        "high_value_items": {}\n    }`,
    solutionSnippet: `def parse_expenses(raw_data: str, threshold: float = 50.0):\n    expenses = {}\n    for item in raw_data.split(','):\n        if ':' in item:\n            cat, amt = item.split(':', 1)\n            expenses[cat.strip()] = float(amt.strip())\n    \n    total = sum(expenses.values())\n    high_value = {k: v for k, v in expenses.items() if v > threshold}\n    return {"total": round(total, 2), "high_value_items": high_value}`,
    successCondition: 'Function correctly parses string input, calculates $275.70 total, and isolates Electronics & Travel.',
    estimatedMinutes: 25,
    skills: ['python-core'],
    category: 'Programming',
    difficulty: 'BEGINNER',
    status: 'AVAILABLE',
  },
  'mission-numpy-pandas': {
    id: 'mission-numpy-pandas',
    title: 'Mission: Customer Churn & Cohort Analysis',
    objective: 'Transform messy user transaction data using Pandas to identify churn rates by customer segment.',
    scenario: 'An e-commerce company needs to understand why users who joined in Q1 stopped purchasing in Q3.',
    whatYouNeed: ['Pandas DataFrame manipulation', 'Groupby aggregations', 'Date resampling', 'Handling missing records'],
    steps: [
      {
        id: 'pd-step-1',
        instruction: 'Load and inspect transactions dataframe, filling missing revenue values with median.',
        hint: 'df["revenue"].fillna(df["revenue"].median(), inplace=True)',
        testCheck: 'Zero remaining null values in revenue column',
      },
      {
        id: 'pd-step-2',
        instruction: 'Group by user cohort month and calculate total lifetime value (LTV).',
        hint: 'df.groupby("cohort_month")["revenue"].sum()',
        testCheck: 'Correctly groups by cohort',
      },
      {
        id: 'pd-step-3',
        instruction: 'Identify top 3 churn risk cohorts with lowest 30-day retention.',
        hint: 'Sort by retention percentage ascending and take head(3).',
        testCheck: 'Returns top 3 at-risk cohort segments',
      },
    ],
    starterCode: `import pandas as pd\nimport numpy as np\n\ndef analyze_cohorts(df):\n    # 1. Clean missing data\n    # 2. Group by cohort\n    # 3. Calculate retention & LTV\n    return df`,
    successCondition: 'Cleaned dataframe passes data auditing test cases and identifies Q1 drop-off pattern.',
    estimatedMinutes: 30,
    skills: ['numpy-pandas', 'statistics-prob'],
    category: 'Data',
    difficulty: 'INTERMEDIATE',
    status: 'AVAILABLE',
  },
  'mission-llm-rag': {
    id: 'mission-llm-rag',
    title: 'Mission: Local Document RAG Search Engine',
    objective: 'Build a miniature semantic vector search engine that retrieves relevant paragraphs for user queries.',
    scenario: 'A company needs an internal tool so employees can ask questions about company policy documents.',
    whatYouNeed: ['Cosine similarity calculation', 'Text embeddings pipeline', 'Top-K ranking', 'Prompt augmentation'],
    steps: [
      {
        id: 'rag-step-1',
        instruction: 'Chunk input document into 200-word overlapping windows.',
        hint: 'Slide window across word tokens with a stride of 150 words.',
        testCheck: 'Generates structured chunk list with metadata',
      },
      {
        id: 'rag-step-2',
        instruction: 'Calculate cosine similarity between query vector and chunk vectors.',
        hint: 'np.dot(vecA, vecB) / (norm(vecA) * norm(vecB))',
        testCheck: 'Calculates accurate vector similarity scores',
      },
      {
        id: 'rag-step-3',
        instruction: 'Assemble context prompt with top-3 chunks and generate response format.',
        hint: 'Join top chunk texts into a formatted SYSTEM prompt.',
        testCheck: 'Produces valid grounded prompt string',
      },
    ],
    starterCode: `def build_rag_context(query: str, documents: list[str]) -> str:\n    # 1. Chunk documents\n    # 2. Compute semantic overlap\n    # 3. Return augmented prompt\n    return ""`,
    successCondition: 'Semantic search matches query against target document section with >0.82 similarity.',
    estimatedMinutes: 35,
    skills: ['llm-rag', 'python-core'],
    category: 'AI & ML',
    difficulty: 'INTERMEDIATE',
    status: 'AVAILABLE',
  },
  'mission-html-css-js': {
    id: 'mission-html-css-js',
    title: 'Mission: Responsive Dark-Mode Task Board',
    objective: 'Create a dynamic Kanban task board in HTML/CSS/JS with task creation, status dragging, and dark mode toggle.',
    scenario: 'You are building the frontend interface for an agile productivity suite.',
    whatYouNeed: ['CSS Grid & Flexbox', 'DOM event delegation', 'LocalStorage persistence', 'CSS custom properties'],
    steps: [
      {
        id: 'web-m1',
        instruction: 'Set up responsive 3-column grid (To-Do, Doing, Done).',
        hint: 'display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));',
        testCheck: 'Responsive columns adapt on window resize',
      },
      {
        id: 'web-m2',
        instruction: 'Implement add task form with validation and dynamic DOM element insertion.',
        hint: 'document.createElement("div") + appendChild',
        testCheck: 'Adds cards without page refresh',
      },
      {
        id: 'web-m3',
        instruction: 'Add theme toggle that switches CSS variables and saves preference to localStorage.',
        hint: 'document.body.classList.toggle("dark-theme")',
        testCheck: 'Theme state persists across reloads',
      },
    ],
    starterCode: `<!-- Index.html -->\n<div class="kanban-board">\n  <div class="col" id="todo"><h3>To Do</h3></div>\n  <div class="col" id="in-progress"><h3>In Progress</h3></div>\n  <div class="col" id="done"><h3>Done</h3></div>\n</div>`,
    successCondition: 'Board dynamically manages task creation and preserves theme in localStorage.',
    estimatedMinutes: 25,
    skills: ['html-css-js'],
    category: 'Frontend',
    difficulty: 'BEGINNER',
    status: 'AVAILABLE',
  },
};

export function createEvidenceFromMission(mission: Mission): EvidenceItem {
  return {
    id: `ev-mission-${Date.now()}`,
    title: `${mission.title}`,
    type: 'MISSION',
    skillId: mission.skills[0] || 'general',
    skillName: mission.title,
    levelEarned: mission.difficulty === 'ADVANCED' ? 4 : mission.difficulty === 'INTERMEDIATE' ? 3 : 2,
    timestamp: new Date().toISOString(),
    proofSummary: `Successfully completed mission: "${mission.objective}". Verified all ${mission.steps.length} implementation requirements.`,
    verifiedBy: 'Avenza Automated Code Verification Testbed',
  };
}
