import { Skill, SkillCategory, Goal } from '../types';

export interface SkillDefinition {
  id: string;
  name: string;
  category: SkillCategory;
  description: string;
  whyItMatters: string;
  prerequisites: string[];
  relatedSkills: string[];
  maxLevel: number;
  levelDescriptions: Record<number, string>;
}

export const SKILL_TAXONOMY: Record<string, SkillDefinition> = {
  'python-core': {
    id: 'python-core',
    name: 'Python Fundamentals',
    category: 'Programming',
    description: 'Variables, loops, data structures (lists, dicts, sets), functions, error handling, and object-oriented basics in Python.',
    whyItMatters: 'Python is the core language for AI, data science, automation, and backend development.',
    prerequisites: [],
    relatedSkills: ['data-structures', 'algorithms', 'numpy-pandas'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Basic syntax, variables, print statements, simple if/else loops',
      2: 'Functions, list comprehensions, dictionary manipulation, file I/O',
      3: 'OOP classes, exception handling, lambda functions, generator expressions',
      4: 'Decorators, context managers, async/await, modular package design',
      5: 'Metaprogramming, C-extensions, deep performance profiling',
    },
  },
  'data-structures': {
    id: 'data-structures',
    name: 'Data Structures & Algorithms',
    category: 'Core CS',
    description: 'Arrays, linked lists, stacks, queues, hash maps, trees, binary search, and Big-O complexity analysis.',
    whyItMatters: 'Essential for writing performant, scalable software and solving complex engineering problems efficiently.',
    prerequisites: ['python-core'],
    relatedSkills: ['python-core', 'algorithms', 'backend-api'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Arrays, basic loops, linear search concept',
      2: 'Stacks, queues, Big-O time and space complexity fundamentals',
      3: 'Hash tables, binary trees, recursion, sorting algorithms (merge/quick)',
      4: 'Graphs, BFS/DFS, dynamic programming, priority queues',
      5: 'Advanced tree balancing (AVL, Red-Black), trie, custom allocator design',
    },
  },
  'numpy-pandas': {
    id: 'numpy-pandas',
    name: 'Data Manipulation (NumPy & Pandas)',
    category: 'Data',
    description: 'Vectorized operations, dataframes, filtering, aggregation, grouping, handling missing values, and exploratory data analysis.',
    whyItMatters: 'Forms the computational backbone for preparing datasets for machine learning models and analytics.',
    prerequisites: ['python-core'],
    relatedSkills: ['python-core', 'statistics-prob', 'data-visualization'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Loading CSVs, inspecting rows/columns with .head() and .info()',
      2: 'Filtering rows, selecting columns, simple summary statistics',
      3: 'Groupby aggregations, merging/joining dataframes, missing value imputation',
      4: 'Vectorized NumPy broadcasting, multi-indexing, time-series resampling',
      5: 'Memory-efficient large dataset processing, custom Cython/C-vectorizers',
    },
  },
  'statistics-prob': {
    id: 'statistics-prob',
    name: 'Statistics & Probability',
    category: 'AI & ML',
    description: 'Descriptive stats, probability distributions, hypothesis testing, Bayes theorem, variance, and regression analysis.',
    whyItMatters: 'Required to interpret ML metrics, evaluate statistical significance, and tune predictive models.',
    prerequisites: [],
    relatedSkills: ['numpy-pandas', 'machine-learning-core'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Mean, median, mode, standard deviation, variance',
      2: 'Probability basics, normal distribution, correlation vs causation',
      3: 'Hypothesis testing (t-tests, p-values), confidence intervals, Bayes rule',
      4: 'Maximum likelihood estimation, multivariate distributions, ANOVA',
      5: 'Stochastic processes, Markov chains, Bayesian inference networks',
    },
  },
  'machine-learning-core': {
    id: 'machine-learning-core',
    name: 'Classical Machine Learning (Scikit-Learn)',
    category: 'AI & ML',
    description: 'Linear/Logistic regression, decision trees, random forests, clustering, model evaluation, cross-validation, and bias-variance tradeoff.',
    whyItMatters: 'Enables computers to learn patterns from data and make predictions without explicit rules.',
    prerequisites: ['python-core', 'numpy-pandas', 'statistics-prob'],
    relatedSkills: ['deep-learning', 'prompt-engineering', 'numpy-pandas'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Understanding supervised vs unsupervised learning concepts',
      2: 'Train/test split, simple Linear Regression and Decision Tree with Scikit-Learn',
      3: 'Cross-validation, precision/recall/F1, Random Forest, Feature scaling',
      4: 'Hyperparameter tuning (GridSearchCV), ensemble methods (XGBoost/LightGBM)',
      5: 'Custom estimator creation, production model monitoring, drift detection',
    },
  },
  'deep-learning': {
    id: 'deep-learning',
    name: 'Deep Learning & Neural Networks',
    category: 'AI & ML',
    description: 'Perceptrons, backpropagation, CNNs for computer vision, RNNs/Transformers for NLP, PyTorch/TensorFlow frameworks.',
    whyItMatters: 'Powers modern AI breakthroughs like computer vision, voice recognition, and large language models.',
    prerequisites: ['machine-learning-core'],
    relatedSkills: ['machine-learning-core', 'llm-rag', 'python-core'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'What is a neuron, forward pass, activation functions (ReLU, Sigmoid)',
      2: 'Building a simple 2-layer MLP in PyTorch for classification',
      3: 'Loss functions, optimizers (Adam, SGD), CNN architecture for images',
      4: 'Attention mechanism, Transformer architecture, transfer learning with HuggingFace',
      5: 'Distributed GPU training, custom CUDA kernels, model quantization (GGML/AWQ)',
    },
  },
  'llm-rag': {
    id: 'llm-rag',
    name: 'LLM Application Dev & RAG',
    category: 'AI & ML',
    description: 'Prompt engineering, embeddings, vector databases (Pinecone/Chroma), retrieval-augmented generation, agents, and tool calling.',
    whyItMatters: 'The current industry standard for building intelligent assistants and enterprise knowledge-retrieval systems.',
    prerequisites: ['python-core', 'deep-learning'],
    relatedSkills: ['python-core', 'backend-api', 'deep-learning'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Making API calls to OpenAI/Gemini, structured prompting',
      2: 'Generating text embeddings and calculating cosine similarity',
      3: 'Building a chunking & vector search pipeline with Chroma/FAISS',
      4: 'Implementing multi-step RAG with re-ranking, source attribution, and LangChain/LlamaIndex',
      5: 'Building autonomous tool-calling agents with memory, guardrails, and latency optimization',
    },
  },
  'html-css-js': {
    id: 'html-css-js',
    name: 'Modern Web Foundations (HTML5, CSS3, JS)',
    category: 'Frontend',
    description: 'Semantic markup, flexbox, grid, DOM manipulation, asynchronous JavaScript (promises, async/await), and event handling.',
    whyItMatters: 'The bedrock of every website, web app, and browser-based user interface.',
    prerequisites: [],
    relatedSkills: ['react-ecosystem', 'typescript'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Basic HTML tags, CSS colors and fonts, simple JS variables',
      2: 'Flexbox, CSS grid, DOM event listeners, basic form handling',
      3: 'Async/await fetch calls, ES6+ modules, responsive design with media queries',
      4: 'Custom CSS animations, Web Components, performance profiling (Lighthouse)',
      5: 'Browser rendering engine pipeline optimization, low-level Canvas/WebGL',
    },
  },
  'typescript': {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Programming',
    description: 'Static typing, interfaces, generics, union types, type guards, type narrowing, and compiler configuration.',
    whyItMatters: 'Prevents runtime bugs, enables great IDE refactoring, and scales codebases cleanly across teams.',
    prerequisites: ['html-css-js'],
    relatedSkills: ['html-css-js', 'react-ecosystem', 'backend-api'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Basic types (string, number, boolean, arrays), simple function signatures',
      2: 'Interfaces, type aliases, optional properties, union types',
      3: 'Generics, type narrowing, enums, DOM event typing',
      4: 'Utility types (Partial, Omit, Record), conditional types, mapped types',
      5: 'Template literal types, AST transformer plugins, advanced type-level computation',
    },
  },
  'react-ecosystem': {
    id: 'react-ecosystem',
    name: 'React & Modern Frontend Architecture',
    category: 'Frontend',
    description: 'Functional components, hooks (useState, useEffect, useMemo), state management, routing, component lifecycles, and modern build tooling.',
    whyItMatters: 'The most widely used UI library for building interactive, component-driven web applications.',
    prerequisites: ['html-css-js', 'typescript'],
    relatedSkills: ['typescript', 'html-css-js', 'backend-api'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'JSX syntax, passing props, rendering lists',
      2: 'useState and useEffect hooks, basic form controlled inputs',
      3: 'Custom hooks, Context API, component composition, error boundaries',
      4: 'Performance optimization (memo, useMemo, useCallback, virtualization), SSR (Next.js)',
      5: 'Concurrent React internals, custom reconciler, micro-frontend architecture',
    },
  },
  'backend-api': {
    id: 'backend-api',
    name: 'Backend APIs & Server Design',
    category: 'Backend',
    description: 'RESTful architecture, FastAPI/Express/Node.js, routing, middleware, request validation, authentication (JWT/OAuth), and CORS.',
    whyItMatters: 'Connects client apps to databases, business logic, and third-party services securely.',
    prerequisites: ['python-core'],
    relatedSkills: ['python-core', 'database-sql', 'git-workflow'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Understanding HTTP methods (GET, POST, PUT, DELETE), JSON responses',
      2: 'Building basic CRUD endpoints with FastAPI or Express',
      3: 'Request validation (Pydantic/Zod), middleware, JWT authentication',
      4: 'Rate limiting, caching (Redis), background workers (Celery/BullMQ)',
      5: 'High-throughput microservice architecture, gRPC, distributed tracing',
    },
  },
  'database-sql': {
    id: 'database-sql',
    name: 'Relational Databases & SQL',
    category: 'Backend',
    description: 'Schema design, normalization, complex SQL queries, JOINs, indexing, transactions, and ACID principles (PostgreSQL).',
    whyItMatters: 'Safely stores, indexes, and queries the world’s structured business data.',
    prerequisites: [],
    relatedSkills: ['backend-api', 'data-structures'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'SELECT, WHERE, ORDER BY, INSERT, UPDATE, DELETE queries',
      2: 'INNER/LEFT JOINs, GROUP BY, aggregations (COUNT, SUM, AVG)',
      3: 'Table schema creation, foreign keys, constraints, subqueries, basic indexing (B-Tree)',
      4: 'Database transactions, query EXPLAIN plan optimization, window functions',
      5: 'Partitioning, sharding, replication topologies, custom query planner tuning',
    },
  },
  'git-workflow': {
    id: 'git-workflow',
    name: 'Git & Version Control',
    category: 'DevOps & Tools',
    description: 'Branching, committing, pull requests, merge conflict resolution, rebasing, and collaborating on GitHub.',
    whyItMatters: 'Standard tool for teamwork, code reviews, deployment pipelines, and project history.',
    prerequisites: [],
    relatedSkills: ['python-core', 'html-css-js'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'git clone, git add, git commit, git push',
      2: 'git branch, git checkout/switch, creating pull requests',
      3: 'Resolving merge conflicts, git stash, understanding git log and diff',
      4: 'Interactive rebase, cherry-pick, git bisect for bug hunting',
      5: 'Git hook automation, repository submodule management, internal object store deep-dive',
    },
  },
  'cybersecurity-basics': {
    id: 'cybersecurity-basics',
    name: 'Security Fundamentals & Web App Security',
    category: 'Cybersecurity',
    description: 'OWASP Top 10 (SQL Injection, XSS, CSRF), network protocols, encryption (symmetric/asymmetric), threat modeling, and secure coding.',
    whyItMatters: 'Protects user data, prevents catastrophic breaches, and ensures compliance.',
    prerequisites: ['backend-api'],
    relatedSkills: ['backend-api', 'database-sql'],
    maxLevel: 5,
    levelDescriptions: {
      1: 'Understanding passwords, HTTPS/SSL concept, phishing basics',
      2: 'Identifying SQL Injection and Cross-Site Scripting (XSS) risks',
      3: 'Implementing CSRF protection, input sanitization, secure headers (CSP)',
      4: 'Threat modeling (STRIDE), automated vulnerability scanning, OAuth2 security flows',
      5: 'Penetration testing, binary exploitation, zero-day analysis',
    },
  },
};

export const STANDARD_GOALS: Goal[] = [
  {
    id: 'goal-ai-engineer',
    title: 'Become an AI / Machine Learning Engineer',
    type: 'CAREER',
    targetRoleOrSkill: 'AI Engineer',
    targetLevel: 4,
    description: 'Master practical Python, statistics, machine learning models, neural networks, and modern LLM / RAG architectures with hands-on projects.',
    estimatedWeeks: 16,
    icon: 'Brain',
    tags: ['AI', 'Python', 'Machine Learning', 'LLMs', 'High Demand'],
    requiredSkills: [
      { skillId: 'python-core', skillName: 'Python Fundamentals', requiredLevel: 4 },
      { skillId: 'numpy-pandas', skillName: 'Data Manipulation (NumPy & Pandas)', requiredLevel: 3 },
      { skillId: 'statistics-prob', skillName: 'Statistics & Probability', requiredLevel: 3 },
      { skillId: 'machine-learning-core', skillName: 'Classical Machine Learning', requiredLevel: 3 },
      { skillId: 'deep-learning', skillName: 'Deep Learning & Neural Networks', requiredLevel: 3 },
      { skillId: 'llm-rag', skillName: 'LLM Application Dev & RAG', requiredLevel: 4 },
      { skillId: 'git-workflow', skillName: 'Git & Version Control', requiredLevel: 2 },
    ],
  },
  {
    id: 'goal-fullstack-dev',
    title: 'Fullstack Web Application Developer',
    type: 'CAREER',
    targetRoleOrSkill: 'Fullstack Developer',
    targetLevel: 4,
    description: 'Build end-to-end web applications with React, TypeScript, backend REST APIs, PostgreSQL databases, and secure authentication.',
    estimatedWeeks: 14,
    icon: 'Layers',
    tags: ['Frontend', 'Backend', 'React', 'TypeScript', 'APIs'],
    requiredSkills: [
      { skillId: 'html-css-js', skillName: 'Modern Web Foundations', requiredLevel: 4 },
      { skillId: 'typescript', skillName: 'TypeScript', requiredLevel: 3 },
      { skillId: 'react-ecosystem', skillName: 'React & Modern Frontend', requiredLevel: 4 },
      { skillId: 'backend-api', skillName: 'Backend APIs & Server Design', requiredLevel: 3 },
      { skillId: 'database-sql', skillName: 'Relational Databases & SQL', requiredLevel: 3 },
      { skillId: 'git-workflow', skillName: 'Git & Version Control', requiredLevel: 3 },
    ],
  },
  {
    id: 'goal-data-analyst',
    title: 'Data Analyst & Insights Specialist',
    type: 'CAREER',
    targetRoleOrSkill: 'Data Analyst',
    targetLevel: 3,
    description: 'Transform raw data into strategic insights using SQL queries, Pandas, statistical modeling, and data storytelling.',
    estimatedWeeks: 10,
    icon: 'BarChart3',
    tags: ['Data', 'SQL', 'Pandas', 'Analytics', 'Business'],
    requiredSkills: [
      { skillId: 'database-sql', skillName: 'Relational Databases & SQL', requiredLevel: 4 },
      { skillId: 'python-core', skillName: 'Python Fundamentals', requiredLevel: 3 },
      { skillId: 'numpy-pandas', skillName: 'Data Manipulation (NumPy & Pandas)', requiredLevel: 4 },
      { skillId: 'statistics-prob', skillName: 'Statistics & Probability', requiredLevel: 3 },
    ],
  },
  {
    id: 'goal-python-mastery',
    title: 'Master Python Programming',
    type: 'SKILL',
    targetRoleOrSkill: 'Python Specialist',
    targetLevel: 4,
    description: 'From syntax to object-oriented architecture, data structures, algorithms, and modular software design.',
    estimatedWeeks: 6,
    icon: 'Code',
    tags: ['Python', 'Foundations', 'Algorithms', 'Beginner Friendly'],
    requiredSkills: [
      { skillId: 'python-core', skillName: 'Python Fundamentals', requiredLevel: 4 },
      { skillId: 'data-structures', skillName: 'Data Structures & Algorithms', requiredLevel: 3 },
      { skillId: 'git-workflow', skillName: 'Git & Version Control', requiredLevel: 2 },
    ],
  },
  {
    id: 'goal-first-ai-app',
    title: 'Build My First AI Product (RAG & Chatbot)',
    type: 'PROJECT',
    targetRoleOrSkill: 'AI Product Builder',
    targetLevel: 3,
    description: 'Ship a working AI-powered customer assistant with custom PDF knowledge retrieval and interactive web UI.',
    estimatedWeeks: 4,
    icon: 'Sparkles',
    tags: ['Project', 'Portfolio', 'Fast Results', 'LLMs'],
    requiredSkills: [
      { skillId: 'python-core', skillName: 'Python Fundamentals', requiredLevel: 2 },
      { skillId: 'backend-api', skillName: 'Backend APIs & Server Design', requiredLevel: 2 },
      { skillId: 'llm-rag', skillName: 'LLM Application Dev & RAG', requiredLevel: 3 },
    ],
  },
];
